packages:
  bed-presence-mk1: !include bed-presence-mk1.yaml

esphome:
  project:
    name: ElevatedSensors.BedPresenceMk1
    version: 2024.9.0

# Allow ESPHome Adoption
dashboard_import:
  package_import_url: github://mikescotland/sensor-configs/bed-presence-mk1.yaml@main
  import_full_config: true

# Allow provisioning Wi-Fi via serial
improv_serial:

# Sets up Bluetooth LE to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none




http_request:
  verify_ssl: true
